# Theoretical Questions:

### Q1.  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?


## Answer :-
### NumPy, short for Numerical Python is a fundamental library for scientific computing and data analysis in Python. Its primary purpose is to provide efficient and powerful tools for handling and processing numerical data 
#### key feature:-
##### 1. Multidimensional Arrays:
- The core feature of NumPy is its "ndarray" object, which supports n-dimensional arrays. This allows for the efficient storage and manipulation of large datasets.

In [2]:
import numpy as np 
l=[1,2,3,]
l1=[4,5,6]
array = np.array([l, l1])
print(array)


[[1 2 3]
 [4 5 6]]


##### 2.Vectorized Operations:
- NumPy supports vectorized operations, which enable element-wise operations on arrays without the need for explicit loops. This leads to more concise and faster code.

In [3]:
a = np.array(l)
b = np.array(l1)
c = a + b

In [4]:
c

array([5, 7, 9])






## Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the import numpy as np
data = np.array([1, 2, 3, 4])
weights = np.array([0.1, 0.2, 0.3, 0.4])
weighted_average = np.average(data, weights=weights)
print(weighted_average)  # Output: 3.0
other?

## answer:
In NumPy, both np.mean() and np.average() are used to calculate the mean of an array, but they have some differences in terms of functionality and use cases.
## np.mean() 
 
- it is used to compute mathmatical calculation along the axis 

In [5]:
import numpy as np
data = np.array([1, 2, 3, 4])
mean_value = np.mean(data)
print(mean_value)  


2.5


## np.avarage()
- it is used to Computes the weighted average along the specified axis.


In [6]:

a=np.array([1, 2, 3, 4])
weights = np.array([0.1, 0.2, 0.3, 0.4])
weighted_average = np.average(a, weights=weights)
print(weighted_average) 


3.0


### we use one over the import numpy as np.mean() and np.average()
- when we  need to calculate the basic arithmetic mean of our data without considering any weightswe we use np.mean()
- When we need to compute a weighted average where different elements have different levels of importance or frequency we use np.average().

## Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

## Answer:
- In NumPy, we can reverse an array along different axes using the numpy.flip() function. This function allows you to flip the order of elements along a specified axis or axes. 
- the methods for reversing NumPy arrays along different axes, with examples for both 1D and 2D arrays:

In [7]:
# Create a 1D array
arr1= np.array([1, 2, 3, 4, 5])

arr_reversed = np.flip(arr1,)



print("Reversed 1D array:", arr_reversed )


Reversed 1D array: [5 4 3 2 1]


In [8]:
# Create a 2D array
arr2 = np.array([[1, 2, 3],
                  [4, 5, 6],
                   [7, 8, 9]])

# Reverse the array along axis 0 (rows)
arr_reversed_rows = np.flip(arr2, axis=0)

# Reverse the array along axis 1 (columns)
arr_reversed_columns = np.flip(arr2, axis=1)

print("Original 2D array:")
print(arr2)
print("\nReversed 2D array (rows):")
print(arr_reversed_rows)
print("\nReversed 2D array (columns):")
print(arr_reversed_columns)


Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reversed 2D array (rows):
[[7 8 9]
 [4 5 6]
 [1 2 3]]

Reversed 2D array (columns):
[[3 2 1]
 [6 5 4]
 [9 8 7]]


## Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

## Answer :
- To determine the data type of elements in a NumPy array using "dtype" attribute of the array 
- For example :- 

In [9]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array(["adarsh","srivastava", "pwskill"])

data_type_a = a.dtype
data_type_b = b.dtype
print("Data type of elements a:", data_type_a)
print("Data type of elements b:", data_type_b)
##  'U10' translates to "Unicode string of maximum length 10,

Data type of elements a: int64
Data type of elements b: <U10


### The importance of data types in memory management and performance in NumPy

#### Memory management in NumPy :
- memory mangement are art to stored in contiguos block of memory (data ) ,allowing for efficient storage and access .Choosing the correct data type ensures that memory usage is optimized.
   - For example, using int8 (1 byte) instead of int64 (8 bytes) for small integers can save a significant amount of memory


#### Performance:

- Operations on NumPy arrays can be significantly faster than on regular Python lists due to vectorization. The choice of data type can affect computational speed. For instance, floating-point operations (float32 or float64) might be slower than integer operations (int32 or int64).

In [10]:
# Array with int64 type
array_int64 = np.array([1, 2, 3, 4, 5], dtype=np.int64)
print("memory usage for int64 array:", array_int64.nbytes, "bytes")

# Array with int8 type
array_int8 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print("memory usage for int8 array:", array_int8.nbytes, "bytes")

memory usage for int64 array: 40 bytes
memory usage for int8 array: 5 bytes


## Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

## Answer:-
### In NumPy ndarray (N-dimensional array) is a powerful **multi-dimensional** array object that is a core component of the NumPy library
#### key feature of ndarray
 ##### 1. **Homogeneous Elements**:
   - All elements in an ndarray must be of the same data type. This uniformity allows for efficient storage and operations.
##### 2. Multi-dimensional:
   - ndarray can have one or more dimensions (1D, 2D, 3D, etc.). The number of dimensions is known as the array’s rank.
##### 3. Efficient Memory Usage:
   - ndarray stores data in contiguous blocks of memory, making it more efficient in terms of both speed and memory usage compared to Python lists.
##### 4. Support for Mathematical Operations:
   - NumPy provides a vast array of functions for element-wise operations, linear algebra, statistical operations, and more, all of which can be applied directly to ndarray objects.
##### 5. Broadcasting:
   - This feature allows NumPy to perform operations on arrays of different shapes, by automatically expanding their shapes to be compatible.
##### 6. Slicing and Indexing:
   - NumPy offers advanced slicing and indexing capabilities that enable the extraction of subarrays and individual elements efficiently.
##### 7. Vectorization:
   - Operations on ndarray are typically vectorized, meaning they are implemented as highly optimized C loops instead of Python loops. This results in significant performance gains.

### Difference between NumPy (ndarray) and Python List :-

- In ndarray all the element in same type but in **list**  all the element can be different .
- ndarray is faster than **list** for numerical computations . ndarray optimized **C**  backend and contiguous memory storage.
- ndarray is more effeciency ( especillay for large array ) besause its compact layout . but in **List** less memory-efficient due to overhead from storing type information and object pointers. 
- ndarray support multidimessional array and do operation on it but in List we have also multidimmensional array but we cannot do operation on all the array and it is also slower than nd array.
- In ndarray Offers advanced slicing, indexing, and broadcasting capabilities but **List** basic slicing and indexingand  no broadcasting.

## Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

## Answer :-
### NumPy arrays (ndarray) offer significant performance benefits over Python lists for large-scale numerical operations. These benefits stem from the way NumPy arrays are implemented and the optimizations they bring to numerical computing.
### Memory Efficiency
 ##### Contiguous Memory Allocation:
- In NumPy Arrays Elements are stored in contiguous blocks of memory, which improves cache performance and reduces memory overhead **but** In Python Lists elements are stored as individual objects with additional pointers and type information, leading to higher memory overhead and scattered memory allocation.
### Example:


In [11]:
import numpy as np
import sys

# NumPy array
array_np = np.arange(100005604)
print("NumPy array memory size:", array_np.nbytes)

# list
List = list(range(1000000))
print("list memory size:", sys.getsizeof(List) + sum(sys.getsizeof(i) for i in List))

NumPy array memory size: 800044832
list memory size: 36000052


### Vectorization:

##### NumPy Arrays: Operations are vectorized, meaning they are implemented as highly optimized C loops. This allows for operations on entire arrays without explicit loops in Python.
##### Python Lists: Require explicit loops or list comprehensions for element-wise operations, which are slower due to Python's loop overhead.
### Example:

In [12]:
import numpy as np
import time


array_np = np.arange(1000000)
list_py = list(range(1000000))


start_np = time.time()
array_np = array_np * 2
end_np = time.time()
print("NumPy array operation time:", end_np - start_np)


start_py = time.time()
list_py = [x * 2 for x in list_py]
end_py = time.time()
print("Python list operation time:", end_py - start_py)

NumPy array operation time: 0.003382444381713867
Python list operation time: 0.0839376449584961


### Broadcasting
- NumPy  can perform operations on arrays of different shapes by automatically broadcasting smaller arrays to the shape of larger ones. This feature eliminates the need for explicit replication of data.
- Python require manual handling and replication of data to achieve similar behavior, which is both error-prone and inefficient.
#### example :

In [13]:
array_np = np.arange(5)
print("Original array:", array_np)
print("Broadcasted addition:", array_np + 10)

Original array: [0 1 2 3 4]
Broadcasted addition: [10 11 12 13 14]


### Optimized Mathematical Functions
- NumPy provide a wide range of optimized mathematical functions (e.g., sin, cos, exp) that operate on entire arrays efficiently.
- but in **Python** **list** require manual implementation using loops or comprehensions, which are less efficient.
#### Example:

In [14]:
import numpy as np
import math

# NumPy mathematical function
n = np.arange(1000000)
start_np = time.time()
result_np = np.sin(n)
end_np = time.time()
print("NumPy sin function time:", end_np - start_np)

# Python list mathematical function
list_py = list(range(1000000))
start_py = time.time()
result_py = [math.sin(x) for x in list_py]
end_py = time.time()
print("Python list sin function time:", end_py - start_py)

NumPy sin function time: 0.028987884521484375
Python list sin function time: 0.2270340919494629


### Ease of Use with Multi-dimensional Data (Multi-dimensional Support)

- NumPy array is natively support multi-dimensional arrays with efficient indexing, slicing, and reshaping operations.
- but in Python lists we  Can simulate multi-dimensional arrays using nested lists, but operations are cumbersome and less efficient.
#### Example:

In [16]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("original 2D array:\n", array_2d)
print("sliced 2D array:\n", array_2d[:, 1])

original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
sliced 2D array:
 [2 5 8]


## Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

### Answer:-
#### vstack()
- vstack() stands for “vertical stack.” It stacks arrays vertically, row-wise. This means it combines arrays along the first axis (axis 0)
### for examples:-

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack((a, b))
print(c)

[[1 2 3]
 [4 5 6]]


### hstack()
- hstack() stands for “horizontal stack.” It stacks arrays horizontally, column-wise. This means it combines arrays along the second axis (axis 1).
### for example:-

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.hstack((a, b))
print(c)

[1 2 3 4 5 6]


## Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

### answer :-
#### fliplr()
- fliplr() stands for **“flip left-right.”** It flips the array in the left/right direction, meaning it reverses the order of columns while keeping the rows intact. This function is useful when we want to mirror an array horizontally.

In [22]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])
flip = np.fliplr(a)
print(flip)


[[3 2 1]
 [6 5 4]]


#### flipud()
- flipud() stands for **“flip up-down.”** It flips the array in the up/down direction, meaning it reverses the order of rows while keeping the columns intact. This function is useful when we want to mirror an array vertically.

In [23]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])
flip = np.flipud(a)
print(flip)


[[4 5 6]
 [1 2 3]]


## Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

### Answer: -
- The array_split() method in NumPy is a versatile tool for dividing an array into multiple sub-arrays. Unlike the split() method, which requires equal-sized splits, array_split() can handle uneven splits gracefully. When you specify the number of splits, it divides the array as evenly as possible, distributing any leftover elements among the first few sub-arrays.

In [26]:
x = np.arange(9)
a = np.array_split(x, 4)
print(a)


[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


- This flexibility makes array_split() particularly useful when dealing with data that doesn’t fit neatly into equal parts, ensuring that the resulting sub-arrays are as balanced as possible.

## Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

 ### Answer:
 
#### Vectorization
- Vectorization is like giving NumPy the ability to handle entire arrays at once, rather than dealing with each element individually. Imagine you have two lists of numbers and you want to add them together. Normally, you might use a loop to add each pair of numbers. With vectorization, you can skip the loop and just tell NumPy to add the arrays directly. This makes your code cleaner and much faster because NumPy uses highly optimized, low-level code to perform these operations.

#### Broadcasting
- Broadcasting is a feature that allows NumPy to perform operations on arrays of different shapes. When you have arrays of different sizes, NumPy can automatically expand the smaller array to match the shape of the larger one. This means you don’t have to manually resize or reshape your arrays.
  For instance, if you want to add a single number to every element of an array, broadcasting makes it simple. NumPy treats the single number as if it were an array of the same size as the original array   and performs the addition.

##### they contribute to efficient array operations
- Both vectorization and broadcasting make your code more efficient and easier to read. They allow you to perform complex operations on large datasets quickly, without writing cumbersome loops. This is especially important in data science and machine learning, where you often work with large arrays of data.

# Practical Questions:

### Q1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [12]:
import numpy as np
array = np.random.randint(1, 101, size=(3, 3))
print(array)

[[70 44 73]
 [39 83 26]
 [72 85  2]]


In [13]:
transposed_array = np.transpose(array)
print(transposed_array)


[[70 39 72]
 [44 83 85]
 [73 26  2]]


### Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [15]:
array=np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


#### Reshape it into a 2x5 array

In [17]:
array1=array.reshape(2,5)
print(array1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Reshape it into a 5x2 array

In [19]:
C=array1.reshape(5,2)
print(array2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array


In [21]:
array = np.random.rand(4, 4)
print(array)

[[0.32159119 0.43874598 0.60530239 0.95085146]
 [0.33545248 0.40367662 0.09452748 0.52972078]
 [0.25256689 0.81125124 0.68156858 0.96500056]
 [0.97816386 0.20038187 0.5926458  0.09992122]]


####  Add a border of zeros around it, resulting in a 6x6 array

In [34]:
array1=np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array1)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.32159119 0.43874598 0.60530239 0.95085146 0.        ]
 [0.         0.33545248 0.40367662 0.09452748 0.52972078 0.        ]
 [0.         0.25256689 0.81125124 0.68156858 0.96500056 0.        ]
 [0.         0.97816386 0.20038187 0.5926458  0.09992122 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


### Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [39]:
array = np.random.randint(10,60, 5)
print(array)

[18 31 55 38 15]


### Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [40]:
array = np.array(['python', 'numpy', 'pandas'])
print(array)

['python' 'numpy' 'pandas']


#### Apply uppercase transformation

In [41]:
array1=np.char.upper(array)
print(array1)

['PYTHON' 'NUMPY' 'PANDAS']


#### Apply lowercase transformatio

In [43]:
array2=np.char.lower(array)
print(array2)

['python' 'numpy' 'pandas']


#### Apply titlecase transformatio

In [44]:
array3=np.char.title(array)
print(array3)

['Python' 'Numpy' 'Pandas']


### Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [46]:
word=np.array(["adarsh","srivastava","shubham","lal"])
#np.array(word)

In [49]:
word1=np.char.join(" ",word)
print(word1)

['a d a r s h' 's r i v a s t a v a' 's h u b h a m' 'l a l']


### Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [72]:
array=np.random.randint(1,100,size=(3,3))
array1=np.random.randint(1,100,size=(3,3))
print("Array :")
print(array)

print("\nArray 1:")
print(array1)

Array :
[[54 67 99]
 [32 40 70]
 [89 24 27]]

Array 1:
[[18 49 70]
 [49 25 69]
 [20 34 94]]


In [71]:
array.ndim

2

In [74]:
add = array + array1
print(add)

[[ 72 116 169]
 [ 81  65 139]
 [109  58 121]]


#### subtraction


In [76]:
subtraction = array-array1
print(subtraction)

[[ 36  18  29]
 [-17  15   1]
 [ 69 -10 -67]]


#### multiplication


In [77]:
multiplication=array*array
print(multiplication)

[[2916 4489 9801]
 [1024 1600 4900]
 [7921  576  729]]


#### division

In [78]:
division=array/array1
print(division)

[[3.         1.36734694 1.41428571]
 [0.65306122 1.6        1.01449275]
 [4.45       0.70588235 0.28723404]]


### Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


In [87]:
array=np.eye(5)
print(array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [88]:
diagonal_array=np.diagonal(array)
print("\n diagonal_array")
print(diagonal_array)



 diagonal_array
[1. 1. 1. 1. 1.]


### Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [96]:
array=np.random.randint(0,1000,100)
print("\n NumPy array of 100 random integers between 0 and 1000")
print(array)



 NumPy array of 100 random integers between 0 and 1000
[ 67 917 825 852 788 739 219 807 421 902 560 864 240 723 743 481 128 175
 140 309 878 799  75 209 986 224 244 512 836 133 677 507 333 750 412 975
 720 823 398 224 366 114 233 401 137 101 616   8 978 962 546 597 523 781
 857 701 593 702 997 871 217 554 445 508 467 446 263 551 641 386 155 991
 802 871 391  95 570 643 765 806 991 460 476 318   8  91 745 316 751 493
 540 310 715  27 922 659 927 381 523  28]


In [93]:
def is_prime(num):
    if num <= 1:
        return False
    elif num <= 3:
        return True
    elif num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

primes = np.array([x for x in array if is_prime(x)])
print("\nPrime numbers in the array:")
print(primes)


Prime numbers in the array:
[571 431  43 853 233 433 107 911 769  47 163 523 251 359 887  89 547  13
 509 523 197 461 733]


### Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [101]:
np.random.seed(0)
temp=np.random.uniform(low=10,high=50,size=30)
print("\n  daily temperatures of month")
print(temp)


  daily temperatures of month
[31.95254016 38.60757465 34.11053504 31.79532732 26.94619197 35.83576452
 27.50348845 45.67092003 48.54651042 25.33766075 41.66900152 31.15579679
 32.72178244 47.02386553 12.84144233 13.48517199 10.8087359  43.30479382
 41.12627004 44.80048593 49.14473369 41.96634257 28.45917449 41.22116705
 14.73097703 35.59684085 15.7341315  47.78675668 30.87393287 26.5864776 ]


In [106]:
weekly_temp=temp.reshape(-1,7)
print("\n weekly_temp")
print(weekly_temp)


 weekly_temp
[[31.95254016 38.60757465 34.11053504 31.79532732 26.94619197 35.83576452
  27.50348845]]


In [107]:
weekly_temp_avg=np.mean(weekly_temp)

32.39306030306593